# Generated by Django 4.0.1 on 2022-01-24 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
